/**
 * Copyright (c) 2026 FinkTech
 *
 * This file is part of MCP Verify.
 * Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
 * See LICENSE file in the project root for full license information.
 */
/**
 * Detector Interface — v2.1
 *
 * Updated to support bidirectional communication with the Smart Fuzzer Engine.
 * Detectors can now receive context hints from the Engine's feedback loop,
 * enabling them to make more accurate decisions without recomputing signals
 * the Engine already calculated.
 *
 * Backwards-compatible: all new fields are optional.
 */

export type DetectionSeverity   = 'low' | 'medium' | 'high' | 'critical';
export type DetectionConfidence = 'low' | 'medium' | 'high' | 'definite';

// ---------------------------------------------------------------------------
// Engine Hint — carries feedback-loop signals from FuzzerEngine → Detectors
// ---------------------------------------------------------------------------

/**
 * Signals computed by the FuzzerEngine's analyzeResponse() that detectors
 * can use as additional evidence without re-deriving them independently.
 *
 * All fields are optional — detectors MUST remain functional when no hint
 * is present (e.g. when called from a test harness or third-party runner).
 */
export interface EngineHint {
  /**
   * Whether the Engine classified this response as anomalous.
   * Maps directly to `ResponseAnalysis.interestLevel !== 'not_interesting'`.
   */
  isAnomaly?: boolean;

  /**
   * The specific reasons the Engine flagged this response.
   * Mirrors `ResponseAnalysis.reasons` from fuzzer-engine.ts.
   */
  anomalyReasons?: ReadonlyArray<
    | 'server_crash'
    | 'timing_anomaly'
    | 'structural_drift'
    | 'error_pattern_match'
    | 'empty_response'
  >;

  /**
   * Whether this payload was generated by the MutationEngine as a
   * follow-up to a previously interesting response.
   */
  isMutation?: boolean;

  /**
   * Which mutation round this payload belongs to (1-based).
   * Round 1 = direct mutation of an interesting payload.
   * Round 2 = mutation of a round-1 mutation, etc.
   */
  mutationRound?: number;

  /**
   * The mutation strategy that produced this payload.
   * Maps to `IMutationStrategy.id` (e.g. 'timing-probe', 'sql-depth').
   */
  mutationStrategy?: string;

  /**
   * The category of the original payload that triggered the mutation chain.
   * Useful when the mutated payload inherits the parent's category.
   */
  originalCategory?: string;

  /**
   * Engine's rolling average response time at the moment of this call (ms).
   * Allows detectors to compute deviation without maintaining their own baseline.
   */
  engineBaselineMs?: number;
}

// ---------------------------------------------------------------------------
// DetectionResult (unchanged from v1)
// ---------------------------------------------------------------------------

export interface DetectionResult {
  /** Whether a vulnerability was detected */
  detected: boolean;
  /** Detector that found the vulnerability */
  detectorId: string;
  /** Type of vulnerability detected */
  vulnerabilityType: string;
  /** Severity of the detected vulnerability */
  severity: DetectionSeverity;
  /** Confidence level in the detection */
  confidence: DetectionConfidence;
  /** Human-readable description of the finding */
  description: string;
  /** Evidence supporting the detection */
  evidence?: {
    payload: string | Record<string, unknown>;
    response: unknown;
    matchedPatterns?: string[];
  };
  /** Remediation suggestions */
  remediation?: string;
  /** CWE ID if applicable */
  cweId?: string;
  /** OWASP category if applicable */
  owaspCategory?: string;
}

// ---------------------------------------------------------------------------
// DetectorContext — extended with optional engine hints
// ---------------------------------------------------------------------------

export interface DetectorContext {
  /** The payload that was sent */
  payload: string | Record<string, unknown>;
  /** The tool name that was called */
  toolName: string;
  /** Response from the server */
  response: unknown;
  /** Response time in milliseconds */
  responseTimeMs: number;
  /** Whether the call resulted in an error */
  isError: boolean;
  /** Error details if applicable */
  error?: {
    code: number;
    message: string;
  };
  /**
   * Optional hints from the FuzzerEngine's feedback loop.
   * When present, detectors SHOULD use these signals as additional evidence
   * to increase or decrease their confidence levels.
   */
  engineHint?: EngineHint;
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// IVulnerabilityDetector (unchanged from v1)
// ---------------------------------------------------------------------------

export interface IVulnerabilityDetector {
  readonly id: string;
  readonly name: string;
  readonly categories?: string[];
  readonly description: string;
  readonly enabledByDefault?: boolean;

  detect(context: DetectorContext): DetectionResult;
  isApplicable(category: string): boolean;
}
