/**
 * Copyright (c) 2026 FinkTech
 *
 * This file is part of MCP Verify.
 * Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
 * See LICENSE file in the project root for full license information.
 */
/**
 * Weak ID / Cryptography Detector
 *
 * Detects predictable or low-entropy identifiers generated by the server.
 * Uses multiple analysis techniques beyond simple entropy:
 *
 * - Shannon Entropy (necessary but not sufficient)
 * - Serial Correlation (lag-1 autocorrelation)
 * - Increment Detection (counters, fixed steps)
 * - Timestamp Detection (embedded Unix timestamps)
 * - Runs Test (Wald-Wolfowitz randomness test)
 * - Pattern Detection (repeated sequences)
 *
 * Also detects weak cryptographic practices:
 * - Weak PRNGs (Math.random, timestamp-based IDs)
 * - Predictable UUIDs (v1 timestamp-based vs v4 random)
 * - Weak hash algorithms (MD5, SHA1)
 * - Insecure JWTs (none algorithm, HS256 with public key confusion)
 *
 * CWE-338: Use of Cryptographically Weak PRNG
 * CWE-327: Use of a Broken or Risky Cryptographic Algorithm
 * CWE-347: Improper Verification of Cryptographic Signature
 */

import {
  IVulnerabilityDetector,
  DetectorContext,
  DetectionResult,
  DetectionConfidence,
  DetectionSeverity
} from './detector.interface';

interface CryptoFinding {
  type: string;
  severity: DetectionSeverity;
  description: string;
  cwe: string;
  evidence?: string;
}

/**
 * Result of predictability analysis
 */
interface PredictabilityResult {
  /** Shannon entropy (bits per character) */
  entropy: number;
  /** Is entropy sufficient? (>= 4.0 for secure IDs) */
  entropyPassed: boolean;

  /** Serial correlation coefficient (-1 to 1, close to 0 is random) */
  serialCorrelation: number;
  /** Is correlation low enough? (|r| < 0.3) */
  correlationPassed: boolean;

  /** Detected increment pattern (null if none) */
  incrementPattern: { step: number; confidence: number } | null;
  /** Are IDs non-incremental? */
  incrementPassed: boolean;

  /** Detected timestamp component */
  timestampComponent: { position: number; type: 'unix_s' | 'unix_ms' | 'sequential' } | null;
  /** Are IDs timestamp-free? */
  timestampPassed: boolean;

  /** Runs test Z-score (|Z| < 1.96 is random at 95% confidence) */
  runsTestZ: number;
  /** Does it pass runs test? */
  runsTestPassed: boolean;

  /**
   * NIST Monobit Test P-value (>= 0.01 passes)
   * Tests if bit frequencies are approximately 50/50
   * Unlike Shannon entropy, this tests cryptographic randomness
   */
  monobitPValue: number;
  /** Does it pass NIST Monobit test? */
  monobitPassed: boolean;

  /**
   * Average Hamming distance between consecutive IDs
   * For truly random IDs, should be ~50% of bit length
   */
  avgHammingDistance: number;
  /** Expected Hamming distance for random sequence */
  expectedHammingDistance: number;
  /** Does Hamming distance look random? (within 20% of expected) */
  hammingPassed: boolean;

  /** Overall: Is the ID generation secure? */
  isSecure: boolean;
  /** Confidence in the analysis */
  confidence: DetectionConfidence;
  /** Human-readable summary */
  summary: string;
}

export interface WeakIdConfig {
  /** Minimum samples needed for statistical ID analysis */
  minSamples?: number;
  /** Enable UUID version detection */
  detectWeakUuid?: boolean;
  /** Enable weak hash detection */
  detectWeakHash?: boolean;
  /** Enable JWT analysis */
  detectWeakJwt?: boolean;
  /** Entropy threshold (default: 4.0) */
  entropyThreshold?: number;
  /** Correlation threshold (default: 0.3) */
  correlationThreshold?: number;
}

export class WeakIdDetector implements IVulnerabilityDetector {
  readonly id = 'weak-id';
  readonly name = 'Weak ID / Cryptography Detector';
  readonly description = 'Detects predictable identifiers using entropy, correlation, and statistical tests (CWE-338)';
  readonly categories = ['cryptography', 'idor', 'authentication'];
  readonly enabledByDefault = true;

  private config: Required<WeakIdConfig>;

  // Internal state to track IDs across multiple requests
  private observedIds: Map<string, string[]> = new Map();
  // Numeric components for statistical analysis
  private numericSamples: Map<string, number[]> = new Map();

  constructor(config: WeakIdConfig = {}) {
    this.config = {
      minSamples: config.minSamples ?? 5,
      detectWeakUuid: config.detectWeakUuid ?? true,
      detectWeakHash: config.detectWeakHash ?? true,
      detectWeakJwt: config.detectWeakJwt ?? true,
      entropyThreshold: config.entropyThreshold ?? 4.0,
      correlationThreshold: config.correlationThreshold ?? 0.3
    };
  }

  // ==================== PATTERN DEFINITIONS ====================

  private readonly weakHashPatterns = [
    {
      pattern: /\b[a-f0-9]{32}\b/gi,
      type: 'MD5',
      bits: 128,
      severity: 'high' as DetectionSeverity,
      cwe: 'CWE-327',
      description: 'MD5 hash detected - cryptographically broken, vulnerable to collision attacks'
    },
    {
      pattern: /\b[a-f0-9]{40}\b/gi,
      type: 'SHA1',
      bits: 160,
      severity: 'medium' as DetectionSeverity,
      cwe: 'CWE-327',
      description: 'SHA1 hash detected - deprecated, vulnerable to collision attacks'
    }
  ];

  private readonly jwtPattern = /eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*/g;

  isApplicable(_category: string): boolean {
    return true;
  }

  detect(context: DetectorContext): DetectionResult {
    const responseStr = this.stringifyResponse(context.response);
    const findings: CryptoFinding[] = [];

    // 1. Check for weak JWTs
    if (this.config.detectWeakJwt) {
      const jwtFindings = this.detectWeakJwts(responseStr);
      findings.push(...jwtFindings);
    }

    // 2. Check for weak hashes
    if (this.config.detectWeakHash) {
      const hashFindings = this.detectWeakHashes(responseStr);
      findings.push(...hashFindings);
    }

    // 3. Check for weak UUIDs (v1 timestamp-based)
    if (this.config.detectWeakUuid) {
      const uuidFindings = this.detectWeakUuids(responseStr);
      findings.push(...uuidFindings);
    }

    // 4. Advanced ID predictability analysis
    const predictabilityFindings = this.analyzeIdPredictability(context, responseStr);
    findings.push(...predictabilityFindings);

    if (findings.length === 0) {
      return this.createEmptyResult();
    }

    // Determine highest severity
    const severityOrder: Record<DetectionSeverity, number> = {
      low: 1, medium: 2, high: 3, critical: 4
    };
    const highestSeverity = findings.reduce((max, f) => {
      return severityOrder[f.severity] > severityOrder[max] ? f.severity : max;
    }, 'low' as DetectionSeverity);

    const confidence: DetectionConfidence = findings.length > 2 ? 'high' : 'medium';
    const descriptions = findings.map(f => f.description).slice(0, 3);
    const types = [...new Set(findings.map(f => f.type))];

    return {
      detectorId: this.id,
      detected: true,
      vulnerabilityType: 'Weak Cryptography / Predictable ID',
      severity: highestSeverity,
      confidence,
      description: `Cryptographic weaknesses detected: ${descriptions.join('; ')}`,
      evidence: {
        payload: context.payload,
        response: this.truncateResponse(context.response),
        matchedPatterns: types
      },
      remediation: this.generateRemediation(findings),
      cweId: this.getPrimaryCwe(findings),
      owaspCategory: 'A02:2021-Cryptographic Failures'
    };
  }

  // ==================== PREDICTABILITY ANALYSIS ====================

  private analyzeIdPredictability(context: DetectorContext, responseStr: string): CryptoFinding[] {
    const findings: CryptoFinding[] = [];

    // Extract potential IDs
    const potentialIds = this.extractIds(responseStr);
    if (potentialIds.length === 0) return findings;

    // Record observed IDs
    if (!this.observedIds.has(context.toolName)) {
      this.observedIds.set(context.toolName, []);
      this.numericSamples.set(context.toolName, []);
    }

    const idSamples = this.observedIds.get(context.toolName)!;
    const numSamples = this.numericSamples.get(context.toolName)!;

    idSamples.push(...potentialIds);

    // Extract numeric components for analysis
    for (const id of potentialIds) {
      const numericPart = this.extractLargestNumeric(id);
      if (numericPart !== null) {
        numSamples.push(numericPart);
      }
    }

    // Need minimum samples for statistical analysis
    if (numSamples.length < this.config.minSamples) {
      return findings;
    }

    // Perform comprehensive predictability analysis
    const analysis = this.performPredictabilityAnalysis(idSamples, numSamples);

    // Generate findings based on analysis
    if (!analysis.isSecure) {
      if (!analysis.incrementPassed && analysis.incrementPattern) {
        findings.push({
          type: 'predictable-increment',
          severity: 'critical',
          description: `Sequential ID pattern detected: increment of ${analysis.incrementPattern.step} with ${(analysis.incrementPattern.confidence * 100).toFixed(0)}% confidence`,
          cwe: 'CWE-338',
          evidence: `Last IDs: ${idSamples.slice(-3).join(', ')}`
        });
      }

      if (!analysis.timestampPassed && analysis.timestampComponent) {
        findings.push({
          type: 'timestamp-based-id',
          severity: 'critical',
          description: `Timestamp-based ID detected: ${analysis.timestampComponent.type} at position ${analysis.timestampComponent.position}`,
          cwe: 'CWE-338',
          evidence: `IDs contain predictable time component`
        });
      }

      if (!analysis.correlationPassed) {
        findings.push({
          type: 'high-serial-correlation',
          severity: 'high',
          description: `High serial correlation (r=${analysis.serialCorrelation.toFixed(3)}) indicates predictable sequence`,
          cwe: 'CWE-338',
          evidence: `Correlation should be < ${this.config.correlationThreshold}`
        });
      }

      if (!analysis.runsTestPassed) {
        findings.push({
          type: 'failed-randomness-test',
          severity: 'high',
          description: `Failed Wald-Wolfowitz runs test (Z=${analysis.runsTestZ.toFixed(2)}): IDs are not random`,
          cwe: 'CWE-338',
          evidence: `Z-score should be between -1.96 and 1.96`
        });
      }

      if (!analysis.entropyPassed) {
        findings.push({
          type: 'low-entropy',
          severity: 'high',
          description: `Low entropy: ${analysis.entropy.toFixed(2)} bits (need >= ${this.config.entropyThreshold})`,
          cwe: 'CWE-338',
          evidence: `Entropy: ${analysis.entropy.toFixed(2)}`
        });
      }

      // NIST Monobit Test - The real cryptographic test
      if (!analysis.monobitPassed) {
        findings.push({
          type: 'failed-nist-monobit',
          severity: 'critical',
          description: `Failed NIST Monobit test (P=${analysis.monobitPValue.toFixed(4)}): bit frequency is biased, not cryptographically random`,
          cwe: 'CWE-338',
          evidence: `P-value ${analysis.monobitPValue.toFixed(4)} < 0.01 threshold. Indicates weak PRNG like Math.random()`
        });
      }

      // Hamming Distance Analysis
      if (!analysis.hammingPassed) {
        const ratio = (analysis.avgHammingDistance / analysis.expectedHammingDistance * 100).toFixed(1);
        findings.push({
          type: 'abnormal-hamming-distance',
          severity: 'high',
          description: `Abnormal Hamming distance: ${analysis.avgHammingDistance.toFixed(1)} bits (expected ~${analysis.expectedHammingDistance.toFixed(1)}, got ${ratio}%)`,
          cwe: 'CWE-338',
          evidence: analysis.avgHammingDistance < analysis.expectedHammingDistance * 0.8
            ? 'Too few bits changing = sequential/counter-based IDs'
            : 'Too many bits changing = possible XOR obfuscation'
        });
      }
    }

    return findings;
  }

  private performPredictabilityAnalysis(ids: string[], numbers: number[]): PredictabilityResult {
    // 1. Shannon Entropy
    const entropy = this.calculateEntropy(ids.join(''));
    const entropyPassed = entropy >= this.config.entropyThreshold;

    // 2. Serial Correlation (lag-1 autocorrelation)
    const serialCorrelation = this.calculateSerialCorrelation(numbers);
    const correlationPassed = Math.abs(serialCorrelation) < this.config.correlationThreshold;

    // 3. Increment Detection
    const incrementPattern = this.detectIncrementPattern(numbers);
    const incrementPassed = incrementPattern === null || incrementPattern.confidence < 0.8;

    // 4. Timestamp Detection
    const timestampComponent = this.detectTimestampComponent(numbers);
    const timestampPassed = timestampComponent === null;

    // 5. Runs Test
    const runsTestZ = this.performRunsTest(numbers);
    const runsTestPassed = Math.abs(runsTestZ) < 1.96; // 95% confidence

    // 6. NIST Monobit Test (NIST SP 800-22)
    // This is the real cryptographic randomness test
    const monobitPValue = this.performMonobitTest(ids);
    const monobitPassed = monobitPValue >= 0.01; // NIST threshold

    // 7. Hamming Distance Analysis
    const hammingResult = this.analyzeHammingDistance(ids);
    const hammingPassed = hammingResult.passed;

    // Overall assessment - now 7 tests
    const passedTests = [
      entropyPassed,
      correlationPassed,
      incrementPassed,
      timestampPassed,
      runsTestPassed,
      monobitPassed,
      hammingPassed
    ];
    const passCount = passedTests.filter(Boolean).length;

    // Need to pass at least 5 of 7 tests for "secure"
    const isSecure = passCount >= 5;
    const confidence: DetectionConfidence = numbers.length >= 10 ? 'high' : 'medium';

    const failedTests: string[] = [];
    if (!entropyPassed) failedTests.push('entropy');
    if (!correlationPassed) failedTests.push('correlation');
    if (!incrementPassed) failedTests.push('increment');
    if (!timestampPassed) failedTests.push('timestamp');
    if (!runsTestPassed) failedTests.push('runs');
    if (!monobitPassed) failedTests.push('monobit');
    if (!hammingPassed) failedTests.push('hamming');

    const summary = isSecure
      ? `ID generation appears secure (passed ${passCount}/7 tests)`
      : `ID generation is WEAK: failed tests: ${failedTests.join(', ')}`;

    return {
      entropy,
      entropyPassed,
      serialCorrelation,
      correlationPassed,
      incrementPattern,
      incrementPassed,
      timestampComponent,
      timestampPassed,
      runsTestZ,
      runsTestPassed,
      monobitPValue,
      monobitPassed,
      avgHammingDistance: hammingResult.avgDistance,
      expectedHammingDistance: hammingResult.expectedDistance,
      hammingPassed,
      isSecure,
      confidence,
      summary
    };
  }

  // ==================== STATISTICAL ANALYSIS METHODS ====================

  /**
   * Calculate Shannon entropy (bits per character)
   */
  private calculateEntropy(str: string): number {
    const len = str.length;
    if (len === 0) return 0;

    const frequencies: Record<string, number> = {};
    for (const char of str) {
      frequencies[char] = (frequencies[char] || 0) + 1;
    }

    return Object.values(frequencies).reduce((sum, freq) => {
      const p = freq / len;
      return sum - p * Math.log2(p);
    }, 0);
  }

  /**
   * Calculate lag-1 serial correlation (autocorrelation)
   * Values close to 0 indicate randomness
   * Values close to 1 or -1 indicate strong patterns
   */
  private calculateSerialCorrelation(values: number[]): number {
    if (values.length < 3) return 0;

    const n = values.length;
    const mean = values.reduce((a, b) => a + b, 0) / n;

    let numerator = 0;
    let denominator = 0;

    for (let i = 0; i < n - 1; i++) {
      numerator += (values[i] - mean) * (values[i + 1] - mean);
    }

    for (let i = 0; i < n; i++) {
      denominator += Math.pow(values[i] - mean, 2);
    }

    if (denominator === 0) return 0;

    return numerator / denominator;
  }

  /**
   * Detect if values follow an increment pattern (counter)
   * Returns the step size and confidence level
   */
  private detectIncrementPattern(values: number[]): { step: number; confidence: number } | null {
    if (values.length < 3) return null;

    // Calculate differences between consecutive values
    const diffs: number[] = [];
    for (let i = 1; i < values.length; i++) {
      diffs.push(values[i] - values[i - 1]);
    }

    // Check if all differences are the same (perfect counter)
    const uniqueDiffs = [...new Set(diffs)];
    if (uniqueDiffs.length === 1 && uniqueDiffs[0] !== 0) {
      return { step: uniqueDiffs[0], confidence: 1.0 };
    }

    // Check for predominant step
    const diffCounts: Record<number, number> = {};
    for (const diff of diffs) {
      diffCounts[diff] = (diffCounts[diff] || 0) + 1;
    }

    const sortedDiffs = Object.entries(diffCounts)
      .map(([diff, count]) => ({ diff: Number(diff), count }))
      .sort((a, b) => b.count - a.count);

    if (sortedDiffs.length > 0 && sortedDiffs[0].diff !== 0) {
      const confidence = sortedDiffs[0].count / diffs.length;
      if (confidence >= 0.7) {
        return { step: sortedDiffs[0].diff, confidence };
      }
    }

    return null;
  }

  /**
   * Detect if values contain timestamp components
   */
  private detectTimestampComponent(values: number[]): { position: number; type: 'unix_s' | 'unix_ms' | 'sequential' } | null {
    if (values.length < 2) return null;

    // Check if values look like Unix timestamps (seconds)
    const now = Date.now() / 1000;
    const recentPast = now - (365 * 24 * 3600); // 1 year ago
    const nearFuture = now + (24 * 3600); // 1 day ahead

    const looksLikeUnixSeconds = values.every(v =>
      v >= recentPast && v <= nearFuture
    );

    if (looksLikeUnixSeconds) {
      // Verify by checking if differences match time elapsed
      const timeDiffs = [];
      for (let i = 1; i < values.length; i++) {
        timeDiffs.push(values[i] - values[i - 1]);
      }
      // If diffs are small and positive, likely timestamps
      const avgDiff = timeDiffs.reduce((a, b) => a + b, 0) / timeDiffs.length;
      if (avgDiff >= 0 && avgDiff < 60) { // Less than 1 minute between samples
        return { position: 0, type: 'unix_s' };
      }
    }

    // Check for Unix milliseconds
    const nowMs = Date.now();
    const recentPastMs = nowMs - (365 * 24 * 3600 * 1000);
    const nearFutureMs = nowMs + (24 * 3600 * 1000);

    const looksLikeUnixMs = values.every(v =>
      v >= recentPastMs && v <= nearFutureMs
    );

    if (looksLikeUnixMs) {
      return { position: 0, type: 'unix_ms' };
    }

    // Check for sequential component (monotonically increasing, small steps)
    let isMonotonic = true;
    for (let i = 1; i < values.length; i++) {
      if (values[i] <= values[i - 1]) {
        isMonotonic = false;
        break;
      }
    }

    if (isMonotonic) {
      const diffs = [];
      for (let i = 1; i < values.length; i++) {
        diffs.push(values[i] - values[i - 1]);
      }
      const avgDiff = diffs.reduce((a, b) => a + b, 0) / diffs.length;
      const maxDiff = Math.max(...diffs);

      // If differences are consistently small, it's a counter
      if (maxDiff < 1000 && avgDiff > 0) {
        return { position: 0, type: 'sequential' };
      }
    }

    return null;
  }

  /**
   * Perform Wald-Wolfowitz runs test for randomness
   * Returns Z-score; |Z| > 1.96 rejects randomness at 95% confidence
   */
  private performRunsTest(values: number[]): number {
    if (values.length < 10) return 0; // Need enough samples

    // Calculate median
    const sorted = [...values].sort((a, b) => a - b);
    const median = sorted[Math.floor(sorted.length / 2)];

    // Convert to binary sequence (above/below median)
    const binary = values.map(v => v >= median ? 1 : 0);

    // Count runs (sequences of same value)
    let runs = 1;
    for (let i = 1; i < binary.length; i++) {
      if (binary[i] !== binary[i - 1]) {
        runs++;
      }
    }

    // Count n1 (above median) and n2 (below median)
    const n1 = binary.filter(b => b === 1).length;
    const n2 = binary.filter(b => b === 0).length;

    if (n1 === 0 || n2 === 0) return 0;

    // Calculate expected runs and standard deviation
    const n = n1 + n2;
    const expectedRuns = ((2 * n1 * n2) / n) + 1;
    const variance = (2 * n1 * n2 * (2 * n1 * n2 - n)) / (n * n * (n - 1));

    if (variance <= 0) return 0;

    const stdDev = Math.sqrt(variance);

    // Calculate Z-score
    const z = (runs - expectedRuns) / stdDev;

    return z;
  }

  /**
   * NIST SP 800-22 Monobit (Frequency) Test
   *
   * This is the fundamental test for cryptographic randomness.
   * Unlike Shannon entropy (which measures compression), this tests
   * if the bit stream has approximately equal 0s and 1s.
   *
   * A biased PRNG like Math.random() with timestamp seeding will fail this.
   * A CSPRNG like crypto.randomBytes() will pass.
   *
   * @param ids Array of ID strings to analyze
   * @returns P-value (>= 0.01 passes, < 0.01 fails)
   */
  private performMonobitTest(ids: string[]): number {
    if (ids.length < 3) return 1.0; // Not enough data, assume pass

    // Convert all IDs to a bit string
    const bitString = this.idsToBitString(ids);
    const n = bitString.length;

    if (n < 100) return 1.0; // NIST recommends at least 100 bits

    // Count the number of 1s
    let sum = 0;
    for (const bit of bitString) {
      sum += bit === '1' ? 1 : -1;
    }

    // Calculate the test statistic
    // S_obs = |sum| / sqrt(n)
    const sObs = Math.abs(sum) / Math.sqrt(n);

    // Calculate P-value using complementary error function
    // P-value = erfc(S_obs / sqrt(2))
    const pValue = this.erfc(sObs / Math.sqrt(2));

    return pValue;
  }

  /**
   * Complementary error function approximation
   * Used for calculating P-values in statistical tests
   */
  private erfc(x: number): number {
    // Horner form coefficients for erfc approximation
    const a1 = 0.254829592;
    const a2 = -0.284496736;
    const a3 = 1.421413741;
    const a4 = -1.453152027;
    const a5 = 1.061405429;
    const p = 0.3275911;

    const sign = x < 0 ? -1 : 1;
    x = Math.abs(x);

    const t = 1.0 / (1.0 + p * x);
    const y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * Math.exp(-x * x);

    return sign === 1 ? 1 - y : 1 + y;
  }

  /**
   * Convert ID strings to a binary bit string
   * Uses hex characters or raw character codes
   */
  private idsToBitString(ids: string[]): string {
    const combined = ids.join('');
    let bits = '';

    for (const char of combined) {
      // If hex character, convert directly
      if (/[0-9a-fA-F]/.test(char)) {
        const nibble = parseInt(char, 16);
        bits += nibble.toString(2).padStart(4, '0');
      } else {
        // Otherwise use character code
        const code = char.charCodeAt(0);
        bits += code.toString(2).padStart(8, '0');
      }
    }

    return bits;
  }

  /**
   * Analyze Hamming distance between consecutive IDs
   *
   * For truly random IDs, the Hamming distance should be approximately
   * 50% of the bit length (half the bits change between random values).
   *
   * PRNGs with weak seeding (like Date.now()) will show suspiciously
   * low or consistent Hamming distances.
   *
   * @param ids Array of ID strings
   * @returns Analysis result with average distance and pass/fail
   */
  private analyzeHammingDistance(ids: string[]): {
    avgDistance: number;
    expectedDistance: number;
    passed: boolean;
  } {
    if (ids.length < 2) {
      return { avgDistance: 0, expectedDistance: 0, passed: true };
    }

    const distances: number[] = [];
    let totalBits = 0;

    for (let i = 1; i < ids.length; i++) {
      const bits1 = this.idsToBitString([ids[i - 1]]);
      const bits2 = this.idsToBitString([ids[i]]);

      // Align lengths
      const maxLen = Math.max(bits1.length, bits2.length);
      const padded1 = bits1.padStart(maxLen, '0');
      const padded2 = bits2.padStart(maxLen, '0');

      // Count differing bits
      let hammingDist = 0;
      for (let j = 0; j < maxLen; j++) {
        if (padded1[j] !== padded2[j]) {
          hammingDist++;
        }
      }

      distances.push(hammingDist);
      totalBits = maxLen;
    }

    if (distances.length === 0) {
      return { avgDistance: 0, expectedDistance: 0, passed: true };
    }

    const avgDistance = distances.reduce((a, b) => a + b, 0) / distances.length;
    const expectedDistance = totalBits * 0.5; // 50% for random

    // Pass if average is within 20% of expected
    // Too low = sequential/predictable
    // Too high = probably XOR-based obfuscation (suspicious)
    const tolerance = 0.2;
    const minExpected = expectedDistance * (1 - tolerance);
    const maxExpected = expectedDistance * (1 + tolerance);

    const passed = avgDistance >= minExpected && avgDistance <= maxExpected;

    return { avgDistance, expectedDistance, passed };
  }

  // ==================== ID EXTRACTION ====================

  private extractIds(text: string): string[] {
    const patterns = [
      /\bEXP-[0-9]+-[0-9]+\b/g,
      /\b[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}\b/gi, // UUID v4
      /\b[0-9a-f]{24}\b/gi, // MongoDB ObjectID
      /\b[A-Za-z0-9_-]{20,}\b/g, // Generic long alphanumeric
    ];

    const ids: string[] = [];
    for (const pattern of patterns) {
      const matches = text.match(pattern);
      if (matches) ids.push(...matches);
    }
    return [...new Set(ids)];
  }

  private extractLargestNumeric(id: string): number | null {
    const matches = id.match(/\d+/g);
    if (!matches) return null;

    // Return the largest numeric component (usually the most significant)
    const numbers = matches.map(m => parseInt(m, 10));
    return Math.max(...numbers);
  }

  // ==================== JWT ANALYSIS ====================

  private detectWeakJwts(text: string): CryptoFinding[] {
    const findings: CryptoFinding[] = [];
    const jwts = text.match(this.jwtPattern) || [];

    for (const jwt of jwts) {
      const parts = jwt.split('.');
      if (parts.length !== 3) continue;

      try {
        const headerJson = this.base64UrlDecode(parts[0]);
        const header = JSON.parse(headerJson);

        if (header.alg === 'none' || header.alg === 'None' || header.alg === 'NONE') {
          findings.push({
            type: 'jwt-alg-none',
            severity: 'critical',
            description: 'JWT with "none" algorithm detected - signature verification disabled',
            cwe: 'CWE-347',
            evidence: jwt.substring(0, 50) + '...'
          });
        }

        if (header.alg === 'HS256' && header.typ === 'JWT') {
          findings.push({
            type: 'jwt-alg-confusion',
            severity: 'high',
            description: 'JWT uses HS256 - vulnerable to key confusion if server uses asymmetric keys',
            cwe: 'CWE-347',
            evidence: jwt.substring(0, 50) + '...'
          });
        }

        const payloadJson = this.base64UrlDecode(parts[1]);
        const payload = JSON.parse(payloadJson);

        if (!payload.exp) {
          findings.push({
            type: 'jwt-no-expiry',
            severity: 'medium',
            description: 'JWT without expiration claim (exp) - token never expires',
            cwe: 'CWE-613',
            evidence: 'Missing "exp" claim'
          });
        }

        if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) {
          findings.push({
            type: 'jwt-expired',
            severity: 'low',
            description: 'Expired JWT returned in response',
            cwe: 'CWE-613',
            evidence: `Expired at: ${new Date(payload.exp * 1000).toISOString()}`
          });
        }

        const sensitiveKeys = ['password', 'secret', 'api_key', 'apiKey', 'private_key'];
        for (const key of sensitiveKeys) {
          if (payload[key]) {
            findings.push({
              type: 'jwt-sensitive-data',
              severity: 'critical',
              description: `JWT contains sensitive data in payload: "${key}"`,
              cwe: 'CWE-200',
              evidence: `Field "${key}" present in JWT payload`
            });
          }
        }

      } catch {
        continue;
      }
    }

    return findings;
  }

  private base64UrlDecode(str: string): string {
    let base64 = str.replace(/-/g, '+').replace(/_/g, '/');
    while (base64.length % 4) {
      base64 += '=';
    }
    return Buffer.from(base64, 'base64').toString('utf-8');
  }

  // ==================== WEAK HASH DETECTION ====================

  private detectWeakHashes(text: string): CryptoFinding[] {
    const findings: CryptoFinding[] = [];

    for (const hashDef of this.weakHashPatterns) {
      const matches = text.match(hashDef.pattern) || [];

      const realHashes = matches.filter(m => {
        if (m.includes('-')) return false;
        if (m.length === 6 && /^[a-f0-9]{6}$/i.test(m)) return false;
        return true;
      });

      if (realHashes.length > 0) {
        findings.push({
          type: `weak-hash-${hashDef.type.toLowerCase()}`,
          severity: hashDef.severity,
          description: hashDef.description,
          cwe: hashDef.cwe,
          evidence: realHashes[0]
        });
      }
    }

    return findings;
  }

  // ==================== WEAK UUID DETECTION ====================

  private detectWeakUuids(text: string): CryptoFinding[] {
    const findings: CryptoFinding[] = [];

    const uuidV1Pattern = /\b[0-9a-f]{8}-[0-9a-f]{4}-1[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}\b/gi;
    const v1Matches = text.match(uuidV1Pattern) || [];

    if (v1Matches.length > 0) {
      findings.push({
        type: 'uuid-v1-timestamp',
        severity: 'high',
        description: 'UUID v1 detected - timestamp-based, predictable and leaks creation time/MAC address',
        cwe: 'CWE-338',
        evidence: v1Matches[0]
      });
    }

    const uuidV3Pattern = /\b[0-9a-f]{8}-[0-9a-f]{4}-3[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}\b/gi;
    const uuidV5Pattern = /\b[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}\b/gi;

    const v3Matches = text.match(uuidV3Pattern) || [];
    const v5Matches = text.match(uuidV5Pattern) || [];

    if (v3Matches.length > 0 || v5Matches.length > 0) {
      findings.push({
        type: 'uuid-deterministic',
        severity: 'medium',
        description: 'UUID v3/v5 detected - deterministic (name-based), may be predictable if inputs are known',
        cwe: 'CWE-338',
        evidence: v3Matches[0] || v5Matches[0]
      });
    }

    return findings;
  }

  // ==================== HELPERS ====================

  private createEmptyResult(): DetectionResult {
    return {
      detectorId: this.id,
      detected: false,
      vulnerabilityType: 'Weak Cryptography',
      severity: 'low',
      confidence: 'low',
      description: 'No cryptographic weaknesses detected',
      evidence: {
        payload: '',
        response: null
      }
    };
  }

  private stringifyResponse(response: unknown): string {
    if (typeof response === 'string') return response;
    try {
      return JSON.stringify(response);
    } catch {
      return String(response);
    }
  }

  private truncateResponse(response: unknown): unknown {
    const str = this.stringifyResponse(response);
    if (str.length > 500) {
      return str.substring(0, 500) + '... [truncated]';
    }
    return response;
  }

  private generateRemediation(findings: CryptoFinding[]): string {
    const remediations: string[] = [];
    const types = new Set(findings.map(f => f.type));

    if (types.has('jwt-alg-none') || types.has('jwt-alg-confusion')) {
      remediations.push('Enforce algorithm validation in JWT library. Whitelist allowed algorithms (RS256/ES256)');
    }
    if (types.has('jwt-no-expiry')) {
      remediations.push('Always include exp (expiration) claim in JWTs');
    }
    if (types.has('jwt-sensitive-data')) {
      remediations.push('Never store sensitive data in JWT payload. Use encrypted JWE or store in database');
    }
    if (types.has('weak-hash-md5') || types.has('weak-hash-sha1')) {
      remediations.push('Use SHA-256 or SHA-3 for hashing. Use bcrypt/argon2 for passwords');
    }
    if (types.has('uuid-v1-timestamp')) {
      remediations.push('Use UUID v4 (random) instead of v1 (timestamp-based)');
    }
    if (types.has('predictable-increment') || types.has('timestamp-based-id')) {
      remediations.push('Use crypto.randomUUID() or crypto.randomBytes() instead of counters or timestamps');
    }
    if (types.has('high-serial-correlation') || types.has('failed-randomness-test')) {
      remediations.push('Replace weak PRNG (Math.random) with cryptographically secure alternatives (crypto.randomBytes)');
    }
    if (types.has('low-entropy')) {
      remediations.push('Increase ID length and character set to improve entropy');
    }
    if (types.has('failed-nist-monobit')) {
      remediations.push('CRITICAL: Your ID generator failed NIST SP 800-22 Monobit test. Use crypto.randomUUID() or crypto.randomBytes() instead of Math.random()');
    }
    if (types.has('abnormal-hamming-distance')) {
      remediations.push('IDs show abnormal bit-flip patterns. Avoid sequential counters, timestamps, or simple XOR obfuscation. Use true cryptographic randomness');
    }

    return remediations.join('. ') || 'Review and strengthen cryptographic implementations';
  }

  private getPrimaryCwe(findings: CryptoFinding[]): string {
    const cwePriority = ['CWE-347', 'CWE-327', 'CWE-338', 'CWE-613', 'CWE-200'];
    for (const cwe of cwePriority) {
      if (findings.some(f => f.cwe === cwe)) {
        return cwe;
      }
    }
    return 'CWE-338';
  }

  /**
   * Reset detector state (for testing or between sessions)
   */
  reset(): void {
    this.observedIds.clear();
    this.numericSamples.clear();
  }

  /**
   * Get analysis results for a tool (for debugging/reporting)
   */
  getAnalysis(toolName: string): PredictabilityResult | null {
    const ids = this.observedIds.get(toolName);
    const nums = this.numericSamples.get(toolName);

    if (!ids || !nums || nums.length < this.config.minSamples) {
      return null;
    }

    return this.performPredictabilityAnalysis(ids, nums);
  }
}
