/**
 * Copyright (c) 2026 FinkTech
 *
 * This file is part of MCP Verify.
 * Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
 * See LICENSE file in the project root for full license information.
 *
 * native-loader.ts
 * ────────────────
 * Loads native Node.js addons (.node files) in a way that works across
 * all three execution contexts of mcp-verify:
 *
 *   Context 1 — Development (ts-node / jest / node dist/mcp-verify.js)
 *     require('@napi-rs/keyring') resolves normally via node_modules.
 *     No special handling needed.
 *
 *   Context 2 — npm install -g mcp-verify
 *     Same as Context 1: npm places the .node files in the global
 *     node_modules tree, and require() finds them without help.
 *
 *   Context 3 — SEA binary (dist/bin/<platform>/mcp-verify[.exe])
 *     There is no node_modules directory. The .node files were copied
 *     next to the executable by copy-native-addons.js. We read the
 *     native-addons.json manifest (also generated by that script) to
 *     discover which specific .node file to load for the current
 *     OS + architecture combination, then call require() with its
 *     absolute path.
 *
 * Usage:
 *   const keyring = loadNativeAddon<typeof import('@napi-rs/keyring')>('@napi-rs/keyring');
 *   if (!keyring) {
 *     // Graceful degradation: credential persistence unavailable
 *   }
 */

import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { t } from "./cli/i18n-helper";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/** Contents of native-addons.json generated by copy-native-addons.js */
interface NativeAddonManifest {
  generatedAt: string;
  generatedBy: string;
  /** Map of package name → array of .node filenames available in this dir */
  addons: Record<string, string[]>;
}

// ─────────────────────────────────────────────────────────────────────────────
// SEA detection
//
// Node 21.7+ exposes require('node:sea').isSea().
// Node 20 LTS does not have this module — we fall back to heuristics.
// We intentionally avoid process._isSEA (undocumented, may disappear).
// ─────────────────────────────────────────────────────────────────────────────

function detectSEA(): boolean {
  // Primary: official node:sea API (Node 21.7+)
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const seaModule = require("node:sea") as { isSea?: () => boolean };
    if (typeof seaModule.isSea === "function") {
      return seaModule.isSea();
    }
  } catch {
    // Module not available (Node 20 LTS) — fall through to heuristics
  }

  // Heuristic for Node 20: if the native-addons.json manifest lives next to
  // the executable, we were almost certainly invoked as a SEA binary.
  // This is intentionally conservative: we only return true when the evidence
  // is unambiguous. False negatives (returning false in SEA) cause a graceful
  // fallback to normal require(), which will then fail with MODULE_NOT_FOUND —
  // a clear error. False positives (returning true in dev) would cause the
  // loader to search for a manifest that doesn't exist and then fall back
  // to normal require() anyway, so they are also harmless.
  const manifestPath = path.join(
    path.dirname(process.execPath),
    "native-addons.json",
  );
  return fs.existsSync(manifestPath);
}

// Evaluated once at module load. Cheap: two try/catch + one fs.existsSync.
const IS_SEA: boolean = detectSEA();

// ─────────────────────────────────────────────────────────────────────────────
// Architecture fingerprinting
//
// @napi-rs packages ship separate .node files per OS + arch + C library.
// We need to pick the right one at runtime.
//
// Linux is the tricky case: the same x64 machine might run glibc (standard
// Ubuntu/Debian/CentOS/RHEL) or musl (Alpine, Docker slim images). We detect
// musl by checking for the musl libc file at its canonical path.
// ─────────────────────────────────────────────────────────────────────────────

type LinuxAbi = "gnu" | "musl";

function detectLinuxAbi(): LinuxAbi {
  // Alpine and musl-based distros ship musl libc at a well-known path.
  // glibc distros do not have this file.
  const muslPaths = [
    "/lib/libc.musl-x86_64.so.1", // x64
    "/lib/libc.musl-aarch64.so.1", // arm64
    "/lib/libc.musl-armhf.so.1", // arm32
    "/usr/lib/x86_64-linux-musl/libc.so", // some Alpine variants
  ];
  return muslPaths.some((p) => fs.existsSync(p)) ? "musl" : "gnu";
}

/** Returns the napi-rs arch/abi suffix for the current platform.
 *  Examples: 'linux-x64-gnu', 'darwin-arm64', 'win32-x64-msvc' */
function currentNapiSuffix(): string {
  const platform = process.platform; // 'linux' | 'darwin' | 'win32'
  const arch = process.arch; // 'x64' | 'arm64' | 'ia32' | ...

  if (platform === "win32") return `win32-${arch}-msvc`;
  if (platform === "darwin") return `darwin-${arch}`;
  if (platform === "linux") return `linux-${arch}-${detectLinuxAbi()}`;

  // Fallback for other Unix-like systems (FreeBSD, etc.) — best effort
  return `${platform}-${arch}-gnu`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Manifest reader
// ─────────────────────────────────────────────────────────────────────────────

let _manifest: NativeAddonManifest | null | undefined = undefined; // undefined = not yet read

function readManifest(): NativeAddonManifest | null {
  if (_manifest !== undefined) return _manifest;

  const manifestPath = path.join(
    path.dirname(process.execPath),
    "native-addons.json",
  );

  try {
    const raw = fs.readFileSync(manifestPath, "utf-8");
    _manifest = JSON.parse(raw) as NativeAddonManifest;
  } catch {
    // Manifest absent or malformed. Not fatal: loadNativeAddon will fall back
    // to normal require() or return null gracefully.
    _manifest = null;
  }

  return _manifest;
}

// ─────────────────────────────────────────────────────────────────────────────
// Core loader
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Attempt to load a .node file from the SEA binary's directory.
 *
 * @param pkg      - npm package name (key in native-addons.json)
 * @param execDir  - directory containing the SEA executable
 * @returns        - the loaded module or null
 */
function loadFromSeaDir<T>(packageName: string, execDir: string): T | null {
  const manifest = readManifest();
  const suffix = currentNapiSuffix();

  // Prefer the exact-match .node file for the current arch/abi, then
  // fall back to any available .node for this package.
  const candidates: string[] = [];

  if (manifest?.addons[packageName]) {
    const files = manifest.addons[packageName];
    // Best candidate: filename contains our exact suffix (e.g. linux-x64-gnu)
    const exact = files.find((f) => f.includes(suffix));
    if (exact) candidates.push(path.join(execDir, exact));
    // Remaining candidates (wrong arch, but worth trying — better than nothing)
    files
      .filter((f) => f !== exact)
      .forEach((f) => candidates.push(path.join(execDir, f)));
  }

  // Last resort: scan the directory for any .node file containing the packageName base name
  const packageNameBase = packageName.split("/").pop() ?? packageName;
  try {
    fs.readdirSync(execDir)
      .filter(
        (f) =>
          f.endsWith(".node") &&
          f.includes(packageNameBase) &&
          !candidates.some((c) => c.endsWith(f)),
      )
      .forEach((f) => candidates.push(path.join(execDir, f)));
  } catch {
    // Unreadable dir — continue with what we have
  }

  for (const candidatePath of candidates) {
    if (!fs.existsSync(candidatePath)) continue;
    try {
      // require() with an absolute path bypasses node_modules resolution entirely.
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      return require(candidatePath) as T;
    } catch {
      // .node compiled for wrong arch/abi — try next candidate
    }
  }

  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Load a native Node.js addon that works across all three execution contexts.
 *
 * @param packageName - npm package name, e.g. '@napi-rs/keyring' or 'fsevents'
 * @param options     - optional overrides
 * @returns           - the loaded module, or null if unavailable
 *
 * @example
 * ```ts
 * import { loadNativeAddon } from '@mcp-verify/core/native-loader';
 * import type Keyring from '@napi-rs/keyring';
 *
 * const keyring = loadNativeAddon<typeof Keyring>('@napi-rs/keyring');
 * if (keyring) {
 *   keyring.setPassword('mcp-verify', 'token', secret);
 * } else {
 *   // Graceful degradation
 *   logger.warn('Keyring unavailable — credentials will not be persisted');
 * }
 * ```
 */
export function loadNativeAddon<T = unknown>(
  packageName: string,
  options: { warnOnMissing?: boolean } = {},
): T | null {
  const { warnOnMissing = false } = options;

  // ── Context 3: SEA binary ──
  if (IS_SEA) {
    const execDir = path.dirname(process.execPath);

    // First, try loading from the SEA binary's directory using the manifest
    const fromSea = loadFromSeaDir<T>(packageName, execDir);
    if (fromSea !== null) return fromSea;

    // Second, try normal require() — handles the case where the user placed
    // the binary inside a node_modules tree (unusual but possible)
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      return require(packageName) as T;
    } catch {
      if (warnOnMissing) {
        // Use process.stderr to avoid going through the logger
        // (this may be called before the logger is initialised)
        process.stderr.write(
          t("mcp_error_native_addon_not_found_sea", {
            addon: packageName,
            dir: execDir,
          }) + "\n",
        );
      }
      return null;
    }
  }

  // ── Contexts 1 & 2: dev / npm install ──
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require(packageName) as T;
  } catch {
    if (warnOnMissing) {
      process.stderr.write(
        t("mcp_error_native_addon_not_installed", { addon: packageName }) +
          "\n",
      );
    }
    return null;
  }
}

/**
 * Convenience: returns true when running as a compiled SEA binary.
 * Useful for conditional behaviour that only makes sense in distribution.
 *
 * @example
 * ```ts
 * if (isSEABinary()) {
 *   logger.debug(`Running as SEA binary from ${process.execPath}`);
 * }
 * ```
 */
export function isSEABinary(): boolean {
  return IS_SEA;
}

/**
 * Returns the directory where native addons are expected when running as SEA.
 * Always returns the directory containing process.execPath.
 * Useful for diagnostics and the doctor command.
 */
export function getNativeAddonDir(): string {
  return path.dirname(process.execPath);
}

/**
 * Returns the loaded manifest, or null if not in SEA mode / manifest missing.
 * Exposed for the `mcp-verify doctor` command to display addon status.
 */
export function getNativeAddonManifest(): NativeAddonManifest | null {
  if (!IS_SEA) return null;
  return readManifest();
}

/**
 * Checks whether a specific native addon is available in the current context.
 * Useful for feature-flag checks without actually loading the module.
 *
 * @example
 * ```ts
 * if (!isNativeAddonAvailable('@napi-rs/keyring')) {
 *   console.warn('Credential persistence is unavailable in this environment.');
 * }
 * ```
 */
export function isNativeAddonAvailable(packageName: string): boolean {
  if (IS_SEA) {
    const execDir = path.dirname(process.execPath);
    const manifest = readManifest();
    const suffix = currentNapiSuffix();

    // Check manifest first (fast path)
    if (manifest?.addons[packageName]?.some((f) => f.includes(suffix)))
      return true;

    // Fall back to filesystem scan
    const packageNameBase = packageName.split("/").pop() ?? packageName;
    try {
      return fs
        .readdirSync(execDir)
        .some((f) => f.endsWith(".node") && f.includes(packageNameBase));
    } catch {
      return false;
    }
  }

  // Dev / npm install: try resolving the package without loading it
  try {
    require.resolve(packageName);
    return true;
  } catch {
    return false;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform helpers (exported for doctor command / diagnostics)
// ─────────────────────────────────────────────────────────────────────────────

/** Returns the napi-rs suffix for the current platform (e.g. 'linux-x64-gnu') */
export function getCurrentNapiSuffix(): string {
  return currentNapiSuffix();
}

/** Returns OS details useful for diagnostics */
export function getPlatformInfo(): {
  platform: string;
  arch: string;
  napiSuffix: string;
  nodeVersion: string;
  isSEA: boolean;
  execPath: string;
  addonDir: string;
} {
  return {
    platform: process.platform,
    arch: process.arch,
    napiSuffix: currentNapiSuffix(),
    nodeVersion: process.version,
    isSEA: IS_SEA,
    execPath: process.execPath,
    addonDir: getNativeAddonDir(),
  };
}
